apiVersion: v1
kind: Pod
metadata:
  name: m-empty-dir
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: mydata
          mountPath: /usr/share/nginx/html
- name: alpine-writer
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
            echo "Hello from Alpine at $(date)" > /data/index.html;
            sleep 5;
          done
      volumeMounts:
        - name: mydata
          mountPath: /data
volumes:
    - name: mydata
      emptyDir: {}
