apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c", "tail -f /dev/null"]
      volumeMounts:
        - name: host-vol
          mountPath: /data
  volumes:
    - name: host-vol
      persistentVolumeClaim:
        claimName: hostpath-pvc